name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.21
      options: -u 1000:100
    steps:
      - uses: actions/checkout@v4

      - name: Hack for Git dubious ownership
        run: git config --global --add safe.directory $PWD

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      # - name: Install Staticcheck
      #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
